### ISSUE TITLE
Fix warning: The `:example_group` key in an example group's metadata hash is deprecated

### ISSUE THREAD

**Issue by ryotarai** [ryotarai/infrataster#38]
With RSpec 3, deprecation warning is shown.

```
The `:example_group` key in an example group's metadata hash is deprecated. Use the example group's hash directly for the computed keys and `:parent_example_group` to access the parent example group metadata instead. Called from /Users/ryota/src/github.com/ryotarai/infrataster/lib/infrataster/contexts.rb:11:in `yield'.
The `:example_group` key in an example group's metadata hash is deprecated. Use the example group's hash directly for the computed keys and `:parent_example_group` to access the parent example group metadata instead. Called from /Users/ryota/src/github.com/ryotarai/infrataster/lib/infrataster/contexts.rb:35:in `yield'.
```

**Comment by mirakui** [comment]
Do you have any plan to solve this warning?

**Comment by ryotarai** [comment]
Hmm, I don't have any plan currently. Before I created this issue, I tried to get example group's metadata without `:example_group` but I couldn't find another way.
Do you have any idea about this issue?

**Comment by otahi** [comment]
Hi @mirakui, @ryotarai 

I am trying to solve this issue.
https://github.com/otahi/infrataster/compare/master...fix_deprecation_of_example_group

I am going to create a WIP pull request for this modification.
Please check it.

**Comment by ryotarai** [comment]
This issue is fixed by @otahi . Thank you very much.
