### ISSUE TITLE
How do you follow a redirect in a form ?

### ISSUE THREAD

**Issue by lowks** [ryotarai/infrataster#45]
I have a login which is redirected from another form then proceeds to login. How do you follow a redirect in infrataster ?

**Comment by legal90** [comment]
@ryotarai I have the same question. Is it possible to make `http` resource to follow redirects? 
For example, I'd like to verify the body of response `https://localhost/` (in TestKitchen). But due to application settings, it returns 302 to some URI `https://localhost/<whatever>`, which I don't care. The only thing I'd like to test is the body content.

**Comment by ryotarai** [comment]
Okay, I'll try to implement a feature to following redirect

**Comment by legal90** [comment]
@ryotarai Thank you! :+1:

**Comment by ryotarai** [comment]
I introduced `follow_redirects` option in v0.3.2. Please try it.

```ruby
  # Redirects
  describe http('http://app.example.com/redirect', follow_redirects: true) do
    it "follows redirects" do
      expect(response.status).to eq(200)
    end
  end
```

**Comment by legal90** [comment]
@ryotarai Seems like it doesn't work for HTTP->HTTPS redirects
```ruby
  describe http('http://127.0.0.1/setup/setupstart.action', ssl: {verify: false}, follow_redirects: true) do
    it 'returns setup wizard' do
      expect(response.status).to eq(200)
      expect(response.body).to include('Set up Confluence')
    end
  end
```

```
         1) server 'confluence_web' http 'http://127.0.0.1/setup/setupstart.action' with {:params=>{}, :method=>:get, :headers=>{}, :ssl=>{:verify=>false}, :follow_redirects=>true} returns setup wizard
            Failure/Error: expect(response.status).to eq(200)
            Faraday::SSLError:
              SSL_connect returned=1 errno=0 state=error: certificate verify failed
```

**Comment by ryotarai** [comment]
Oh...I didn't check combination of ssl and follow_redirects options. I'll fix it.

**Comment by ryotarai** [comment]
I added [tests with both `ssl: {verify: false}` and `follow_redirects: true`](https://github.com/ryotarai/infrataster/commit/30cb3c7170eeb53ffb5c1c0718472dbd34f7d986
) and it passed.
