### ISSUE TITLE
https resource for infrataster

### ISSUE THREAD

**Issue by SnehaM** [ryotarai/infrataster#47]
Currently I am testing HTTPS response when sending HTTPS request.
So I am planning to add https resource in infrataster.
I can use rubygem faraday (same as http resource) for developing this resource.
And the authentication options like client certification, client key etc can be passed to farday ssl options.
I think this resource will be useful for other users of infrataster.
What is your opinion about it?

**Comment by SnehaM** [comment]
Please find pull request https://github.com/ryotarai/infrataster/pull/48

**Comment by ryotarai** [comment]
`ssl` option is supported since v0.2.1 thanks to @SnehaM
