### ISSUE TITLE
memcached plugin for infrataster

### ISSUE THREAD

**Issue by rahulkhengare** [ryotarai/infrataster#55]
Currently I am working on testing database servers in combination with memcached servers using infrataster.

Memcached:
Memcached is an in-memory key-value store for small chunks of arbitrary data. 
For more details about memcached refer, 
http://memcached.org/ 

I am planning to develop memcached plugin for infrataster. This plugin used to query memcached server to check the statistics of server, set and get the values from server.

This plugin will useful for other users also.
Please share your thoughts.

**Comment by ryotarai** [comment]
memcached plugin is very good idea.
If you create the one, please tell me that. I'll add it to README.

**Comment by rahulkhengare** [comment]
I have implemented plugins for memcached server, the plugin is tested on linux machine.

Plugin Source:
https://github.com/rahulkhengare/infrataster-plugin-memcached

Kindly review the plugin. 
Your thoughts and suggestions will be greatly appreciated

**Comment by ryotarai** [comment]
I think [this global variable](https://github.com/rahulkhengare/infrataster-plugin-memcached/blob/master/lib/infrataster/contexts/memcached_context.rb#L21) is dirty for namespace and instance or class variables is better.

The plugin looks good to me except the point I mentioned.

**Comment by rahulkhengare** [comment]
Thanks for review.

I have changed the code as per review comments. Convert global variable to instance variable.
Kindly have a look.

Commit Link:
https://github.com/rahulkhengare/infrataster-plugin-memcached/commit/05b7fdf4e2095308f430f8e1ed2a933a8ec0d2c0

**Comment by ryotarai** [comment]
It looks good to me! I'll introduce your plugin in README.

**Comment by rahulkhengare** [comment]
Thank you very much for including memcached plugin.
I really appreciate it.
