### ISSUE TITLE
Redis plugin for infrataster

### ISSUE THREAD

**Issue by rahulkhengare** [ryotarai/infrataster#59]
I have implemented plugins for REDIS server, the plugin is tested on linux machine.

Plugin Source:
https://github.com/rahulkhengare/infrataster-plugin-redis

Kindly review the plugin.
Your thoughts and suggestions will be greatly appreciated

**Comment by ryotarai** [comment]
I introduce it in README. https://github.com/ryotarai/infrataster/commit/ecadce687ebb744e07ea535c7cfff9076cf88d7a

Thank you for creating a plugin!

**Comment by rahulkhengare** [comment]
Thank you very much for including redis plugin.
I really appreciate it.
