### ISSUE TITLE
Testing a HTTPS resource results in NoMethodError exception

### ISSUE THREAD

**Issue by ghost** [ryotarai/infrataster#74]
(English speakers scroll down for solution)

Infrataster version: 0.32
Ruby version: 2.4.1p111

specファイルでhttpsリソースを指定してinfratasterを実行するとNoMethodErrorが発生します。

spec_helper.rbのinfrataster向けの内容：

```ruby
require 'infrataster/rspec'

Infrataster::Server.define(
    :reddit,
    'www.reddit.com'
)
```

specダイレクトリーでの対応するspecファイル内容：

```ruby
require 'spec_helper'

describe server(:reddit) do
    describe http('https://www.reddit.com') do
        it "responds content including 'Want to join'" do
            expect(response.body).to include('Want to join')
        end
    end
end
```
他のサイトにもやってみたんですけど、どうやらhttpsだとこのexceptionは発生します。httpだけだと無事で実行します。

これを再現できますか？または、上記の内容は何かが間違ってるでしょうか？

よろしくお願いします。

**Comment by ryotarai** [comment]
backtraceやexceptionの詳細をもらえますか

**Comment by ghost** [comment]
失礼しました。

```
F

Failures:

  1) server 'reddit' http 'https://www.reddit.com' with {:params=>{}, :method=>:get, :headers=>{}} responds content including 'Want to join'
     Failure/Error: expect(response.body).to include('Want to join')
     
     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./spec/reddit_spec.rb:6:in `block (3 levels) in <top (required)>'

Finished in 0.0026 seconds (files took 0.44493 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/reddit_spec.rb:5 # server 'reddit' http 'https://www.reddit.com' with {:params=>{}, :method=>:get, :headers=>{}} responds content including 'Want to join'
```

**Comment by ghost** [comment]
ssl: {verify: false}を付けると解決しますが、faradayで発生したエラーの影響でこのエラーが出てるわけですかね？

なぜDigiCertの証明書はverifyできないのはfaradayの方で調べてみますので、こちらの方は単純にエラーハンドリングの問題だけでしょうかね？

lib/infrataster/contexts/http_context.rb:17: `conn = Faraday.new(options) do |faraday|`で発生してるようです。

**Comment by ghost** [comment]
申し訳ないです、どうやらfaraday0.12からのバグみたいなんです、infratasterと関係ないです：　https://github.com/lostisland/faraday/issues/694

このコミットを試してみたらinfratasterのhttpsは直りました：　https://github.com/lostisland/faraday/pull/706/files

faraday0.12.2を利用すると解決するはずです（まだリリースできてないですけど）。

To anybody else reading this thread, if you're experiencing this error try upgrading your faraday gem to 0.12.2 or greater.

**Comment by ghost** [comment]
Faraday 0.12.2がリリースされて、上記の問題を解決するのを確認できます。
